"""Regenerate textscan_data.go from local Unicode 17.0.0 data files.

Download https://www.unicode.org/Public/17.0.0/security/confusables.txt and
https://www.unicode.org/Public/17.0.0/emoji/emoji-test.txt, then run:
python3 internal/model/generate_textscan.py confusables.txt emoji-test.txt
golangci-lint fmt

Only non-ASCII sources with entirely ASCII alphanumeric skeletons are selected:
punctuation lookalikes (curly quotes, dashes, spaces) are ordinary prose.
All listed emoji qualifications are accepted, including text-style variants.
The generated emoji exceptions only contain sequences the scanner could flag.
"""

import hashlib
import pathlib
import sys
import unicodedata


def quote(text):
    # Keep every non-ASCII codepoint visible to reviewers, including the hidden
    # characters this scanner detects. Go uses \U escapes, not surrogate pairs.
    return '"' + ''.join(
        chr(r) if 32 <= r < 127 and chr(r) not in '\\"' else
        f'\\u{r:04x}' if r <= 0xffff else f'\\U{r:08x}'
        for r in map(ord, text)
    ) + '"'


confusables_file, emoji_file = map(pathlib.Path, sys.argv[1:])
confusables_text = confusables_file.read_text()
emoji_text = emoji_file.read_text()
assert '# Version: 17.0.0' in confusables_text
assert '# Version: 17.0' in emoji_text

confusables = set()
for line in confusables_text.splitlines():
    fields = line.split('#', 1)[0].split(';')
    if len(fields) < 2:
        continue
    source = chr(int(fields[0].strip(), 16))
    target = ''.join(chr(int(r, 16)) for r in fields[1].split())
    if ord(source) > 127 and target.isascii() and target.isalnum():
        confusables.add(source)

emoji = set()
for line in emoji_text.splitlines():
    fields = line.split('#', 1)[0].split(';')
    if len(fields) < 2:
        continue
    sequence = ''.join(chr(int(r, 16)) for r in fields[0].split())
    if any(r in confusables or unicodedata.category(r) == 'Cf'
           or 0xfe00 <= ord(r) <= 0xfe0f for r in sequence):
        emoji.add(sequence)

lines = [
    '// Code generated by generate_textscan.py; DO NOT EDIT.',
    '// Unicode 17.0.0 data, copyright Unicode, Inc.',
    '// See LICENSE-UNICODE.txt at the repository root for the Unicode License V3.',
    '// Sources and regeneration instructions are in generate_textscan.py.',
    '// confusables.txt SHA-256: ' + hashlib.sha256(confusables_file.read_bytes()).hexdigest(),
    '// emoji-test.txt SHA-256: ' + hashlib.sha256(emoji_file.read_bytes()).hexdigest(),
    '', 'package model', '',
]
chars = ''.join(sorted(confusables))
lines.append('const asciiConfusables = ' + quote(chars[:16]) + ' +')
for pos in range(16, len(chars), 16):
    lines.append('\t' + quote(chars[pos:pos + 16]) + (' +' if pos + 16 < len(chars) else ''))
lines.extend(['', 'var scanEmoji = map[string]struct{}{'])
lines.extend('\t' + quote(sequence) + ': {},' for sequence in sorted(emoji))
lines.append('}')
pathlib.Path(__file__).with_name('textscan_data.go').write_text('\n'.join(lines) + '\n')
print(f'Generated {len(confusables)} confusable characters and {len(emoji)} emoji exceptions.')
